name: resource_importer
description:  Imports resource files as string or binary literals in Dart code.
version: 0.2.0
repository: https://github.com/jamesderlin/dart_resource_importer

executables:
  resource_importer:

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  basics: ^0.10.0
  build: ^3.0.0
  charcode: ^1.3.1
  crypto: ^3.0.6
  dart_style: ^3.0.0
  file: ^7.0.0
  logging: ^1.3.0
  yaml: ^3.1.3

dev_dependencies:
  dartbag: ^0.7.0
  test: ^1.26.2


dependency_overrides:
  analyzer: ^8.0.0